### ISSUE TITLE
fix match buffer oversize panic - memory usage

### ISSUE THREAD

**Issue by akfaew** [iohub/ahocorasick#14]
Hey, I have a question about the latest commit: https://github.com/iohub/ahocorasick/commit/bb845ee1e2dd5727cfd637db7c4f7c42e0f53de9

Supposed we have a 1MB text that looks like this: "aaaaaaaa...aaa"
And keywords that look like this: ["a", "aa", "aaa", ... ]

Will the algorithm not take a whole lot of memory? There will be 1M matches of "a", 1M-1 matches of "aa" etc. This will probably exhaust all system memory but please correct me if I understood it wrong.

**Comment by iohub** [comment]
you're right, this commit cause big bug. but I don't want use dynamic slice because that would cause GC overhead. I just use it for splited streaming text. so I ignore this problem. 
do you have any suggestions?

**Comment by iohub** [comment]
I tried not output all matched item in Match() function, replace with a python yield like function "NextMatchItem()", the occupied memories is normal. so I would like try this way.

**Comment by iohub** [comment]
I tried not output all matched item in Match() function, replace with a python yield like function "NextMatchItem()", the occupied memories is normal. so I would like try this way.

**Comment by iohub** [comment]
now you can try the case by matcher_test.go in
```
func TestHugeMatching(t *testing.T) {
	m := NewMatcher()
	cLen := 1024 * 12
	fmt.Printf("\ntesting in near [%v]^2 matchs case...\n", cLen)
	content := "a"
	for ix := 0; ix < cLen; ix++ {
		m.Insert([]byte(content), ix)
		content += "a"
	}
	m.Compile()
	seq := []byte(content)
	m.Match(seq)
	ix := 0
	for m.HasNext() {
		for _, item := range m.NextMatchItem(seq) {
			ix++
			key := m.Key(seq, item)
			if ix%1000 == 0 && len(key) != 0 {
				// fmt.Printf("key Len:%v value:%d\n", len(key), item.Value.(int))
			}
		}
	}
	fmt.Println("done")
}
```
I changed  `cLen := 1024 * 12` to `cLen := 1024 * 1024` it work well

**Comment by akfaew** [comment]
Consider a real world scenario where you allow the user to enter 100 keywords to search a website. He maliciously enters the keywords to be "a", "aa", "aaa", ... and the website is 1MB of "aaa...a". For this realistic scenario the algorithm fails, and is not safe to use in production where we operate on user-provided data. Notice that not only will the memory be squared, but also the time. It is fast to search, but slow to prepare the result.

I think that a function like the `MatchVals()` that I proposed would be safe, it would not use so much memory because each keyword can be matched only once and it would be much faster.
