### ISSUE TITLE
Issues with concurrency

### ISSUE THREAD

**Issue by YeruchamB** [iohub/ahocorasick#18]
I'm getting transient errors when trying to create multiple automaton in different threads. I keep getting panic: runtime error: index out of range [-x] errors that pop up in different places while building the automatons.

When you state that _"This package is not thread safe if there is one goroutine doing insertions or deletions."_, does that mean even when each thread is accessing a different automaton?

**Comment by iohub** [comment]
You can add a mutex lock wrap for concurrency usage.
