### ISSUE TITLE
How many word dictionary trees can ahocorasick build at most

### ISSUE THREAD

**Issue by coderfeaker** [iohub/ahocorasick#19]
I build with 4000W key-value,occur erro 
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x5069d0, 0x16)
	/home/work/local/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc664000000, 0x400000000, 0x5f6438)
	/home/work/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x5dc060, 0x400000000, 0x429d17, 0x5dc068)
	/home/work/local/go/src/runtime/malloc.go:727 +0x1e5
runtime.(*mheap).grow(0x5dc060, 0x200000, 0x0)
	/home/work/local/go/src/runtime/mheap.go:1344 +0x85
runtime.(*mheap).allocSpan(0x5dc060, 0x200000, 0xc00c880100, 0x5f6448, 0xfffffffffffffade)
	/home/work/local/go/src/runtime/mheap.go:1160 +0x6b6
runtime.(*mheap).alloc.func1()
	/home/work/local/go/src/runtime/mheap.go:907 +0x65
runtime.(*mheap).alloc(0x5dc060, 0x200000, 0x450101, 0x5dc060)
	/home/work/local/go/src/runtime/mheap.go:901 +0x85
runtime.largeAlloc(0x400000000, 0x5f0101, 0x7ff8a5b59080)
	/home/work/local/go/src/runtime/malloc.go:1177 +0x92
runtime.mallocgc.func1()
	/home/work/local/go/src/runtime/malloc.go:1071 +0x46
runtime.systemstack(0x0)
	/home/work/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/home/work/local/go/src/runtime/proc.go:1116

**Comment by iohub** [comment]
I haven't tested the limit of load words, but 40 million words seems  to be too large for a single machine.
