### ISSUE TITLE
Loading a large number of strings_ index out of range

### ISSUE THREAD

**Issue by annapras** [iohub/ahocorasick#6]
I am getting an error when searching against a large number of strings. It works with 5 million strings but fails from around 7 million strings..is there any limit to number of strings loaded and can it be adjusted...

The error is 
Runtime error  index out of range
Trace..cedar.go.line 320《- acmatcher.go line 138

Any suggestions to allow for more strings

**Comment by iohub** [comment]
could you give me some test data?
